### ISSUE TITLE
any plans for websys-webRTC transport?

### ISSUE THREAD

**Issue by DougAnderson444** [vincev/libp2p-websys-transport#5]
Vince, very cool library for the browser. 
I was wondering if there are any plans in the works to also make one for WebRTC transport via web-sys?

**Comment by vincev** [comment]
Thank you @DougAnderson444, the libp2p team has it as a plan [here](https://github.com/libp2p/rust-libp2p/blob/master/ROADMAP.md#improved-wasm-support), I think they have already implemented the server part maybe @mxinden can comment.

**Comment by vincev** [comment]
@DougAnderson444 going to close this, if you are not in a hurry probably the best thing to do is to wait for the libp2p team to work their magic, you can follow the progress on the specs [here](https://github.com/libp2p/specs/pull/497).

**Comment by DougAnderson444** [comment]
Ok, thanks Vince!

**Comment by mxinden** [comment]
> Vince, very cool library for the browser.

Great to see more implementations of `Transport` @vincev!

> I think they have already implemented the server part maybe @mxinden can comment.

Correct. See https://github.com/libp2p/rust-libp2p/tree/master/transports/webrtc

There are two libp2p WebRTCs:

- browser-to-server https://github.com/libp2p/specs/blob/master/webrtc/README.md
  - Implemented in rust-libp2p as a server
  - Implemented in js-libp2p as a client
- browser-to-browser (or private-to-private) https://github.com/libp2p/specs/pull/497
  - Implemented in js-libp2p https://github.com/libp2p/js-libp2p-webrtc/pull/90

While the server part of browser-to-server is already released as an alpha in rust-libp2p, I would very much like to see the browser side (via WASM) in rust-libp2p as well.

Once that is in place, I don't think implementing the browser-to-browser specification for rust-libp2p is a big endeavor.

> to wait for the libp2p team to work their magic

I don't think we (rust-libp2p maintainers) will get to either of the above planned implementations in Q1 or Q2. Help would be very much appreciated. It opens a hole new use-case for rust-libp2p. Happy to support in any way I can.

**Comment by mxinden** [comment]
Happy to meet and discuss this further in one of the upcoming rust-libp2p open maintainer calls with @thomaseizinger and me.

https://github.com/libp2p/rust-libp2p/discussions/3604
