### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by thomaseizinger** [vincev/libp2p-websys-transport#6]
Hi from `rust-libp2p`!

Just a heads-up that you could reduce your dependency tree by switching from `libp2p` to `libp2p-core`. Not only is that more lightweight, it might also reduce the number of breaking changes you have to go through.

We are [working](https://github.com/libp2p/rust-libp2p/issues/3271) on making it easier to maintain external transports as well, so eventually you will be able to depend on a `libp2p-transport` crate that is just a thin interface.

**Comment by vincev** [comment]
Hi @thomaseizinger thank you for the heads-up, this looks nice I am going to make the switch.
